window.SENTENCES_AUDIO_MAP = {
  "Can we borrow books at the library?": "assets/audios/tts/fish_q_0_09b488d8.mp3",
  "Yes, we can.": "assets/audios/tts/fish_opt_c9edac14.mp3",
  "No, we can't.": "assets/audios/tts/fish_opt_2945b998.mp3",
  "Yes, we walk.": "assets/audios/tts/fish_opt_b214fcfd.mp3",
  "Can you take a taxi to the airport?": "assets/audios/tts/fish_q_1_327618c6.mp3",
  "Yes, I can.": "assets/audios/tts/fish_opt_3b925184.mp3",
  "No, I can't.": "assets/audios/tts/fish_opt_5617396f.mp3",
  "No, I hospital.": "assets/audios/tts/fish_opt_29f07fb1.mp3",
  "Where do you go to buy medicine?": "assets/audios/tts/fish_q_2_bc58121d.mp3",
  "pharmacy": "assets/audios/tts/fish_opt_bf4e2878.mp3",
  "park": "assets/audios/tts/fish_opt_fb45615c.mp3",
  "zoo": "assets/audios/tts/fish_opt_d2cbe65f.mp3",
  "Where can you see wild animals?": "assets/audios/tts/fish_q_3_75de6b69.mp3",
  "bank": "assets/audios/tts/fish_opt_bd5af1f6.mp3",
  "library": "assets/audios/tts/fish_opt_d521f765.mp3",
  "Which vehicle puts out fires?": "assets/audios/tts/fish_q_4_f2b42d47.mp3",
  "fire truck": "assets/audios/tts/fish_opt_afc8ae19.mp3",
  "taxi": "assets/audios/tts/fish_opt_35e768d3.mp3",
  "bus": "assets/audios/tts/fish_opt_d20f83ee.mp3",
  "Which vehicle takes patients?": "assets/audios/tts/fish_q_5_b26506c0.mp3",
  "ambulance": "assets/audios/tts/fish_opt_e0d0f09d.mp3",
  "tow truck": "assets/audios/tts/fish_opt_f5f9995a.mp3",
  "police car": "assets/audios/tts/fish_opt_02b13d6a.mp3"
};
